version: '3.9'

services:
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

  n8n:
    image: n8nio/n8n
    restart: always
    env_file:
      - .env
    networks:
      - web

  webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    env_file:
      - .env
    networks:
      - web

  ollama:
    image: ollama/ollama
    restart: always
    ports:
      - "11434:11434"
    networks:
      - web

  portainer:
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:
  portainer_data:

networks:
  web:
    driver: bridge
